### ISSUE TITLE
Hide Borders for Skin Art (and download)

### ISSUE THREAD

**Issue by mwomo** [NameMC-Extras/NameMC-Extras#22]
I dont see the option to download the Skin Art, only the hiding borders option. Is this a bug on my end or is this part of the update?

![image](https://github.com/NameMC-Extras/NameMC-Extras/assets/173872758/4d20a4d3-66a6-4fb4-81d9-d0ce85b77639)

**Comment by bribes** [comment]
Oh sorry I removed it as I didn’t think anyone actuslly used it Lmaoo I’ll readd it soon.

**Comment by mwomo** [comment]
It's okay lol. I just use it to get yk skin art ideas lmao

**Comment by bribes** [comment]
> It's okay lol. I just use it to get yk skin art ideas lmao

Alright will be fixed in a update that should come out in the coming days.
